Changed the function name
AfterLutz/Akkatecture pull request #76
Opened 2022-02-08 13:58 UTC by Aman-Mandal

Changed the function name in commandTest.cs file

2022-02-09 16:09 UTC, malclear requested changes

2022-02-09 16:09 UTC, malclear commented on test/Akkatecture.Tests/UnitTests/Commands/CommandTests.cs
> +        public void InstantiatingCommand_WithValidInput_ThrowsException_Succeeds()
Can you take out the "ThrowsExceptions" part of the name? There are none raised in this particular test.

2022-02-09 16:18 UTC, malclear commented
I've put a comment in your PR.
Thanks!!
*Malcolm Learner*


On Tue, Feb 8, 2022 at 7:58 AM Aman Mandal ***@***.***> wrote:

> Changed the function name in commandTest.cs file
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/AfterLutz/Akkatecture/pull/76
> Commit Summary
>
>    - 6947e2b
>    <https://github.com/AfterLutz/Akkatecture/pull/76/commits/6947e2b6aa36f5ac7ecb2a8f8156774f3635c985>
>    Changed the function name in commandTest.cs
>
> File Changes
>
> (1 file <https://github.com/AfterLutz/Akkatecture/pull/76/files>)
>
>    - *M* test/Akkatecture.Tests/UnitTests/Commands/CommandTests.cs
>    <https://github.com/AfterLutz/Akkatecture/pull/76/files#diff-8f1e736d79f6f07befa0f9cf39a2542e998a956e52ef4175718078bf0d8d9f6f>
>    (2)
>
> Patch Links:
>
>    - https://github.com/AfterLutz/Akkatecture/pull/76.patch
>    - https://github.com/AfterLutz/Akkatecture/pull/76.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AfterLutz/Akkatecture/pull/76>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACY3VUO332X37F2UNEOSHTLU2EORVANCNFSM5N2RJDDA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-02-10 10:37 UTC, Aman-Mandal commented
So all I have to do is remove the "ThrowsException" from the name right sir?

2022-02-10 10:42 UTC, Aman-Mandal commented
Done Sir .. !! Is this fine ?

2022-02-16 04:27 UTC, merged